require "user.options"
require "user.keymaps"
require "user.functions"

require "user.lazynvim"
-- require "user.packer"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.lazygit"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.toggleterm"
require "user.whichkey"
require "user.copilot"
require "user.lualine"
require "user.indent_blankline"
require "user.hop";


